<?php

/**
 * @file
 * Contains image_field_to_media.module.
 */

use Drupal\media\MediaInterface;

/**
 * Implements hook_ENTITY_TYPE_delete() for media entity.
 *
 * Delete from the storage the hash of the image file related with the deleted
 * media entity.
 */
function filefield_to_mediafield_media_delete(MediaInterface $media) {
  $mid = $media->id();
  $hashes = \Drupal::state()->get('filefield_to_mediafield.hashes_of_image_files');
  unset($hashes[$mid]);
  \Drupal::state()->set('filefield_to_mediafield.hashes_of_image_files', $hashes);
}
